version: '3.5'
services:
  odoo:
    build:
      context: ./addons
    container_name: odoo_meworld
    networks:
      - coolify
    volumes:
      - './config/odoo.conf:/etc/odoo/odoo.conf'
      - './odoo-web-data:/var/lib/odoo'
networks:
  coolify:
    external: trues
