version: '3.5'

services:
  odoo:
    build:
      context: ./addons
    container_name: odoo_antesco
    networks:
      - coolify
    volumes:
      - './config/odoo.conf:/etc/odoo/odoo.conf'
      - './odoo-web-data:/var/lib/odoo'
    restart: unless-stopped

  ai-chat:
    build:
      context: ./ai-chat
    container_name: ai_chat_ui
    working_dir: /app
    command: 'sh -c "npm install && npm run dev"'
    ports:
      - '3039:3000'
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true