{
    "name": "Data Sync from HanoiCheck",
    "version": "17.0.1.0.65",
    "category": "Inventory",
    "summary": "Import data from the HanoiCheck supplier API",
    "depends": ["product", "sale", "base_setup"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/product_template_views.xml",
        "views/production_site_views.xml",
        "views/res_partner_views.xml",
        "views/supplier_contract_views.xml",
        "views/sync_wizard_views.xml",
        "views/crall_material_menus.xml",
    ],
    "external_dependencies": {"python": ["requests"]},
    "installable": True,
    "application": True,
}